/*
 * spcc — spacelang compiler.
 *
 * High-level design (compiler+lib distribution, gcc-style)
 * --------------------------------------------------------
 * spcc compiles a .sp source into a standalone native executable by
 * emitting a small C file and shelling out to a C compiler that links it
 * against a pre-built runtime archive (libspci.a) and the runtime header
 * (spci.h).
 *
 * Distribution model: spcc + spci.h + libspci.a ship together in a known
 * directory (`SPACELANG_ROOT`), conceptually like gcc + libgcc.a + headers
 * under $GOROOT-style discoverable layout. The compiled output binary is
 * fully self-contained — the archive is statically linked in.
 *
 * Runtime lookup, in order:
 *   1. $SPACELANG_ROOT (if set)
 *   2. dirname(realpath(argv[0]))   — handy in dev when spcc sits next
 *                                     to spci.h / libspci.a in c/
 * The first location containing both spci.h and libspci.a wins.
 *
 * Generated file is small (~1 KB): just `#include "spci.h"`, the user's
 * .sp source as a byte array, and a generated main() that calls
 * feed(SP_SOURCE). cc compiles + links it against libspci.a.
 *
 * Mesh contract: the generated binary speaks the existing spci mesh
 * protocol. Identity from SPACELANG_NAME / SPACELANG_BUS or --name/--bus
 * on the generated binary. --serve keeps it alive after feed() returns.
 *
 * CLI
 *   spcc input.sp -o output           compile to ./output
 *   spcc --emit-c input.sp            print generated C to stdout
 *   spcc --keep-c input.sp -o output  also write output.c next to binary
 *   spcc --cc gcc input.sp -o output  override $CC (default: cc)
 *   spcc --debug input.sp -o output   compile with -g -O0, implies --keep-c
 *   spcc --root DIR input.sp ...      override runtime-source lookup
 */

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <libgen.h>
#include <errno.h>
#include <limits.h>

static void die(const char *msg) {
    fprintf(stderr, "spcc: %s\n", msg);
    exit(1);
}

static char *slurp(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); exit(1); }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(n + 1);
    if (!buf) die("oom");
    if (fread(buf, 1, n, f) != (size_t)n) die("short read");
    buf[n] = 0;
    fclose(f);
    if (out_len) *out_len = (size_t)n;
    return buf;
}

static int file_exists(const char *path) {
    struct stat st;
    return stat(path, &st) == 0 && S_ISREG(st.st_mode);
}

static int root_has_runtime(const char *root) {
    char p[PATH_MAX];
    snprintf(p, sizeof p, "%s/spci.h",    root); if (!file_exists(p)) return 0;
    snprintf(p, sizeof p, "%s/libspci.a", root); if (!file_exists(p)) return 0;
    return 1;
}

/* find SPACELANG_ROOT — env override, then next to the spcc binary. */
static char *find_root(void) {
    const char *env = getenv("SPACELANG_ROOT");
    if (env && *env && root_has_runtime(env)) return strdup(env);

    char exe[PATH_MAX];
    ssize_t n = readlink("/proc/self/exe", exe, sizeof exe - 1);
    if (n > 0) {
        exe[n] = 0;
        char *dup = strdup(exe);
        char *d = dirname(dup);
        if (root_has_runtime(d)) { char *r = strdup(d); free(dup); return r; }
        free(dup);
    }
    return NULL;
}

static void emit(FILE *out, const char *sp_src, size_t sp_len, const char *bake_name) {
    fputs("/* generated by spcc - do not edit by hand */\n", out);
    fputs("#define _POSIX_C_SOURCE 200809L\n", out);
    fputs("#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n", out);
    fputs("#include \"spci.h\"\n", out);

    fputs("\nstatic const char SP_SOURCE[] = {\n", out);
    for (size_t i = 0; i < sp_len; i++) {
        fprintf(out, "0x%02x,", (unsigned char)sp_src[i]);
        if ((i & 15) == 15) fputc('\n', out);
    }
    fputs("0x00};\n", out);

    fputs(
        "\n"
        "int main(int argc, char **argv) {\n"
        "    setvbuf(stdout, NULL, _IOLBF, 0);\n"
        "    setvbuf(stderr, NULL, _IOLBF, 0);\n"
        "    const char *env_name = getenv(\"SPACELANG_NAME\");\n"
        "    const char *env_bus  = getenv(\"SPACELANG_BUS\");\n",
        out);
    if (bake_name) fprintf(out, "    my_name = strdup(\"%s\");\n", bake_name);
    fputs(
        "    if (env_name) my_name = strdup(env_name);\n"
        "    if (env_bus)  bus_dir = strdup(env_bus);\n"
        "    int keep_alive = 0;\n"
        "    for (int i = 1; i < argc; i++) {\n"
        "        if (!strcmp(argv[i], \"--name\") && i+1<argc) my_name = argv[++i];\n"
        "        else if (!strcmp(argv[i], \"--bus\") && i+1<argc) bus_dir = argv[++i];\n"
        "        else if (!strcmp(argv[i], \"--serve\")) keep_alive = 1;\n"
        "    }\n"
        "    if (my_name && !bus_dir) bus_dir = (char*)\"/tmp/spacelang\";\n"
        "    if (my_name) { if (mesh_listen() < 0) return 1; }\n"
        "    feed(SP_SOURCE);\n"
        "    if (my_name && keep_alive) { for (;;) mesh_poll(1000); }\n"
        "    return 0;\n"
        "}\n",
        out);
}

static int run_cc(const char *cc, const char *root,
                  const char *cfile, const char *output, int debug) {
    char lib[PATH_MAX], inc[PATH_MAX + 2];
    snprintf(lib, sizeof lib, "%s/libspci.a", root);
    snprintf(inc, sizeof inc, "-I%s", root);

    pid_t pid = fork();
    if (pid < 0) { perror("fork"); return -1; }
    if (pid == 0) {
        if (debug)
            execlp(cc, cc, "-g", "-O0", "-w", inc, cfile, lib, "-o", output, (char*)NULL);
        else
            execlp(cc, cc, "-O2",       "-w", inc, cfile, lib, "-o", output, (char*)NULL);
        perror(cc);
        _exit(127);
    }
    int status = 0;
    if (waitpid(pid, &status, 0) < 0) { perror("waitpid"); return -1; }
    if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) return -1;
    return 0;
}

static void usage(void) {
    fputs(
        "usage: spcc [--emit-c] [--keep-c] [--debug] [--cc CC] [--root DIR]\n"
        "            input.sp [-o output]\n",
        stderr);
}

int main(int argc, char **argv) {
    const char *input = NULL;
    const char *output = NULL;
    const char *cc = getenv("CC");
    if (!cc || !*cc) cc = "cc";
    const char *root_override = NULL;
    const char *bake_name = NULL;
    int emit_c_only = 0;
    int keep_c = 0;
    int debug = 0;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--emit-c")) emit_c_only = 1;
        else if (!strcmp(argv[i], "--keep-c")) keep_c = 1;
        else if (!strcmp(argv[i], "--debug") || !strcmp(argv[i], "-g")) { debug = 1; keep_c = 1; }
        else if (!strcmp(argv[i], "--cc") && i+1 < argc) cc = argv[++i];
        else if (!strcmp(argv[i], "--root") && i+1 < argc) root_override = argv[++i];
        else if (!strcmp(argv[i], "--as") && i+1 < argc) bake_name = argv[++i];
        else if (!strcmp(argv[i], "-o") && i+1 < argc) output = argv[++i];
        else if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) { usage(); return 0; }
        else if (argv[i][0] == '-') {
            fprintf(stderr, "spcc: unknown flag: %s\n", argv[i]);
            usage(); return 1;
        }
        else input = argv[i];
    }
    if (!input) { usage(); return 1; }
    if (!emit_c_only && !output) {
        size_t n = strlen(input);
        char *o = malloc(n + 5);
        memcpy(o, input, n + 1);
        if (n > 3 && !strcmp(o + n - 3, ".sp")) o[n-3] = 0;
        else strcat(o, ".out");
        output = o;
    }

    char *root = NULL;
    if (root_override) {
        if (!root_has_runtime(root_override)) {
            fprintf(stderr, "spcc: --root %s: missing spci.h/libspci.a\n", root_override);
            return 1;
        }
        root = strdup(root_override);
    } else {
        root = find_root();
        if (!root) {
            fprintf(stderr,
                "spcc: cannot locate runtime (spci.h, libspci.a).\n"
                "      Set SPACELANG_ROOT or pass --root DIR.\n");
            return 1;
        }
    }

    size_t sp_len = 0;
    char *sp_src = slurp(input, &sp_len);

    if (emit_c_only) {
        emit(stdout, sp_src, sp_len, bake_name);
        free(sp_src); free(root);
        return 0;
    }

    char cpath[PATH_MAX];
    if (keep_c) snprintf(cpath, sizeof cpath, "%s.c", output);
    else        snprintf(cpath, sizeof cpath, "/tmp/spcc-%d.c", (int)getpid());

    FILE *cf = fopen(cpath, "wb");
    if (!cf) { perror(cpath); return 1; }
    emit(cf, sp_src, sp_len, bake_name);
    fclose(cf);
    free(sp_src);

    int rc = run_cc(cc, root, cpath, output, debug);
    if (!keep_c) unlink(cpath);
    free(root);
    if (rc != 0) { fprintf(stderr, "spcc: %s failed\n", cc); return 3; }
    return 0;
}
