/*
 * spcc — spacelang compiler.
 *
 * High-level design
 * -----------------
 * spcc compiles a .sp source file into a standalone native executable by
 * emitting a single self-contained C file and shelling out to a C compiler.
 *
 * Approach for v1: "packaging compiler".
 *   - The generated .c contains the entire spci runtime (parser + values +
 *     stack + dict + builtins + mesh transport) followed by the user
 *     program embedded as a byte array and a small generated main() that
 *     calls feed(SP_SOURCE) on it.
 *   - Two blobs are linked into spcc at build time via xxd -i:
 *       spci_h_blob (the contents of spci.h)
 *       spci_c_blob (the contents of spci.c)
 *     The header is emitted first so the runtime sees its own declarations
 *     without needing a separate include path at compile-of-generated time.
 *   - spci.c no longer contains main(); that lives in spci_main.c. The
 *     compiled binary supplies its own generated main() instead.
 *
 * What this buys us:
 *   - Standalone binaries with no install footprint.
 *   - Identical semantics to spci, by construction (same eval loop,
 *     same builtins, same mesh transport).
 *   - Full language including mesh ops ($, $!, $?).
 *
 * What it does NOT buy (and why that's OK for v1):
 *   - No speedup over the interpreter — generated code still threads
 *     through feed() / eval(). A future v2 would lower the AST to opcode
 *     arrays plus a tiny switch-based evaluator and inline builtin
 *     dispatch.
 *
 * Mesh contract:
 *   - The generated binary speaks the existing spci mesh protocol unchanged.
 *   - Identity comes from SPACELANG_NAME / SPACELANG_BUS env vars or
 *     --name / --bus flags on the generated binary itself.
 *   - --serve makes the binary stay alive after feed() returns so peers
 *     can keep reaching it. Without --serve, it runs the program and exits.
 *   - Orchestration (spawning peers, lifecycle) lives in the separate
 *     `spco` component and is out of scope here.
 *
 * CLI
 *   spcc input.sp -o output           compile to ./output
 *   spcc --emit-c input.sp            print generated C to stdout, no compile
 *   spcc --keep-c input.sp -o output  also write output.c next to the binary
 *   spcc --cc gcc input.sp -o output  override $CC (default: cc)
 *
 * Build
 *   make c/spcc   (depends on c/spci_blob.h, which xxd -i's both spci.{h,c})
 */

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <errno.h>

#include "spci_blob.h"
/* spci_blob.h provides:
 *   unsigned char spci_h[]; unsigned int spci_h_len;
 *   unsigned char spci_c[]; unsigned int spci_c_len;
 */

static void die(const char *msg) {
    fprintf(stderr, "spcc: %s\n", msg);
    exit(1);
}

static char *slurp(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); exit(1); }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(n + 1);
    if (!buf) die("oom");
    if (fread(buf, 1, n, f) != (size_t)n) die("short read");
    buf[n] = 0;
    fclose(f);
    if (out_len) *out_len = (size_t)n;
    return buf;
}

/* The runtime's spci.c starts with `#include "spci.h"`. In the generated
 * single-file output, that include can't resolve. We strip it by skipping
 * the first occurrence of the matching line when emitting the runtime. */
static void emit_runtime_stripping_self_include(FILE *out) {
    const char *needle = "#include \"spci.h\"";
    size_t nlen = strlen(needle);
    /* find first occurrence */
    size_t hit = (size_t)-1;
    for (size_t i = 0; i + nlen <= spci_c_len; i++) {
        if (memcmp(spci_c + i, needle, nlen) == 0) { hit = i; break; }
    }
    if (hit == (size_t)-1) {
        fwrite(spci_c, 1, spci_c_len, out);
        return;
    }
    /* extend hit to end of line */
    size_t end = hit + nlen;
    while (end < spci_c_len && spci_c[end] != '\n') end++;
    if (end < spci_c_len) end++; /* eat the newline */
    fwrite(spci_c, 1, hit, out);
    fwrite(spci_c + end, 1, spci_c_len - end, out);
}

static void emit(FILE *out, const char *sp_src, size_t sp_len) {
    fputs("/* generated by spcc - do not edit by hand */\n", out);

    /* 1. Inline the public header so the runtime sees its own decls. */
    fwrite(spci_h, 1, spci_h_len, out);
    fputc('\n', out);

    /* 2. Inline the runtime (with its self-include stripped). */
    emit_runtime_stripping_self_include(out);
    fputc('\n', out);

    /* 3. Embed the user program as a NUL-terminated byte array. */
    fputs("\nstatic const char SP_SOURCE[] = {\n", out);
    for (size_t i = 0; i < sp_len; i++) {
        fprintf(out, "0x%02x,", (unsigned char)sp_src[i]);
        if ((i & 15) == 15) fputc('\n', out);
    }
    fputs("0x00};\n", out);

    /* 4. Generated driver — uses the public surface from spci.h. */
    fputs(
        "\n"
        "int main(int argc, char **argv) {\n"
        "    setvbuf(stdout, NULL, _IOLBF, 0);\n"
        "    setvbuf(stderr, NULL, _IOLBF, 0);\n"
        "    const char *env_name = getenv(\"SPACELANG_NAME\");\n"
        "    const char *env_bus  = getenv(\"SPACELANG_BUS\");\n"
        "    if (env_name) my_name = strdup(env_name);\n"
        "    if (env_bus)  bus_dir = strdup(env_bus);\n"
        "    int keep_alive = 0;\n"
        "    for (int i = 1; i < argc; i++) {\n"
        "        if (!strcmp(argv[i], \"--name\") && i+1<argc) my_name = argv[++i];\n"
        "        else if (!strcmp(argv[i], \"--bus\") && i+1<argc) bus_dir = argv[++i];\n"
        "        else if (!strcmp(argv[i], \"--serve\")) keep_alive = 1;\n"
        "    }\n"
        "    if (my_name && !bus_dir) bus_dir = (char*)\"/tmp/spacelang\";\n"
        "    if (my_name) { if (mesh_listen() < 0) return 1; }\n"
        "    feed(SP_SOURCE);\n"
        "    if (my_name && keep_alive) { for (;;) mesh_poll(1000); }\n"
        "    return 0;\n"
        "}\n",
        out);
}

static int run_cc(const char *cc, const char *cfile, const char *output, int debug) {
    pid_t pid = fork();
    if (pid < 0) { perror("fork"); return -1; }
    if (pid == 0) {
        if (debug)
            execlp(cc, cc, "-g", "-O0", "-w", cfile, "-o", output, (char*)NULL);
        else
            execlp(cc, cc, "-O2", "-w", cfile, "-o", output, (char*)NULL);
        perror(cc);
        _exit(127);
    }
    int status = 0;
    if (waitpid(pid, &status, 0) < 0) { perror("waitpid"); return -1; }
    if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) return -1;
    return 0;
}

static void usage(void) {
    fputs(
        "usage: spcc [--emit-c] [--keep-c] [--cc CC] input.sp [-o output]\n",
        stderr);
}

int main(int argc, char **argv) {
    const char *input = NULL;
    const char *output = NULL;
    const char *cc = getenv("CC");
    if (!cc || !*cc) cc = "cc";
    int emit_c_only = 0;
    int keep_c = 0;
    int debug = 0;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--emit-c")) emit_c_only = 1;
        else if (!strcmp(argv[i], "--keep-c")) keep_c = 1;
        else if (!strcmp(argv[i], "--debug") || !strcmp(argv[i], "-g")) { debug = 1; keep_c = 1; }
        else if (!strcmp(argv[i], "--cc") && i+1 < argc) cc = argv[++i];
        else if (!strcmp(argv[i], "-o") && i+1 < argc) output = argv[++i];
        else if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
            usage(); return 0;
        }
        else if (argv[i][0] == '-') {
            fprintf(stderr, "spcc: unknown flag: %s\n", argv[i]);
            usage(); return 1;
        }
        else input = argv[i];
    }
    if (!input) { usage(); return 1; }
    if (!emit_c_only && !output) {
        size_t n = strlen(input);
        char *o = malloc(n + 5);
        memcpy(o, input, n + 1);
        if (n > 3 && !strcmp(o + n - 3, ".sp")) o[n-3] = 0;
        else strcat(o, ".out");
        output = o;
    }

    size_t sp_len = 0;
    char *sp_src = slurp(input, &sp_len);

    if (emit_c_only) {
        emit(stdout, sp_src, sp_len);
        free(sp_src);
        return 0;
    }

    char cpath[4096];
    if (keep_c) snprintf(cpath, sizeof cpath, "%s.c", output);
    else        snprintf(cpath, sizeof cpath, "/tmp/spcc-%d.c", (int)getpid());

    FILE *cf = fopen(cpath, "wb");
    if (!cf) { perror(cpath); return 1; }
    emit(cf, sp_src, sp_len);
    fclose(cf);
    free(sp_src);

    int rc = run_cc(cc, cpath, output, debug);
    if (!keep_c) unlink(cpath);
    if (rc != 0) { fprintf(stderr, "spcc: %s failed\n", cc); return 3; }
    return 0;
}
